apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello-iyjy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello-iyjy
    app.kubernetes.io/part-of: my-app-1
  name: node-express-hello-iyjy
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: node-express-hello-iyjy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: node-express-hello-iyjy
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/karthik-jk-tenant/my-app-1/node-express-hello-iyjy@sha256:5653c3f09e90b89288953c2639a71c1142652e9c89455e9b1fde524caf50e98f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
